LibraryPlus/urls.py
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),          
    path('auth/', include("appAuth.urls")),       
    path('accounts/', include('django.contrib.auth.urls')), 
    path('__debug__/', include(debug_toolbar.urls)), 
    path('', include("appAuth.urls")),
    path("home/", include("barcodeRec.urls")),
    path("profile/", include("userProfile.urls")),
    path('updateMode/', views.updateMode, name='updateMode'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appAuth/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from django.urls import path
from . import views

urlpatterns = [
    path("", views.login, name="login"),
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("successfulLogin/", views.successfulLogin, name="success"),
    path("fail/", views.fail, name="fail"),
]

userProfile/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.profile_view, name='profile'),
    path('saved-books/', views.saved_books_view, name='saved_books'),
    path('my-ratings/', views.my_ratings_view, name='my_ratings'),
]

userProfile/models.py
from django.db import models
from django.contrib.auth.models import User
from .choices import USER_TYPE_CHOICES

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=20, choices=USER_TYPE_CHOICES, default='User')
    bio = models.TextField(blank=True)
    profile_picture = models.ImageField(upload_to='profiles/', blank=True, null=True)
    birth_date = models.DateField(null=True, blank=True)
    display_mode = models.CharField(max_length=6, default='light')

    def __str__(self):
        return f"{self.user.username} - {self.user_type}"

userProfile/views.py
import csv
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from userProfile.decorators import user_type_required
from .models import UserProfile
from barcodeRec.models import Rating, Book
import random
from isbnlib import *


@login_required
def profile_view(request):
    if request.method == 'POST' and request.FILES.get('profile_picture'):
        profile = request.user.userprofile
        profile.profile_picture = request.FILES['profile_picture']
        profile.save()
        return redirect('profile')  
    return render(request, "userProfile/profile.html", {'random_number': random.randint(0, 7)})

@login_required
@user_type_required('User')
def saved_books_view(request):
    if request.method == 'POST':
        searchTitle = request.POST['search']
        if searchTitle:
            user_books = Book.objects.filter(user=request.user, title__icontains=searchTitle).order_by('title')
        else:
            user_books = Book.objects.filter(user=request.user).order_by('title')
    else:
        user_books = Book.objects.filter(user=request.user).order_by('title')

    return render(request, 'userProfile/myBooks.html', {'books': user_books, 'random_number': random.randint(0, 7)})

@login_required
@user_type_required('User')
def my_ratings_view(request):

    if request.method == 'POST':
        searchTitle = request.POST['search']
        if searchTitle:
            user_ratings = Rating.objects.filter(user=request.user, title__icontains=searchTitle).order_by('-rated_at')
        else:
            user_ratings = Rating.objects.filter(user=request.user).order_by('-rated_at')
    else:
        user_ratings = Rating.objects.filter(user=request.user).order_by('-rated_at')

    return render(request, 'userProfile/myRatings.html', {'ratings': user_ratings, 'random_number': random.randint(0, 7)})

@login_required
@user_type_required('Librarie')
def manage_books(request):

    books = Book.objects.all().order_by('title')

    # books = Book.objects.all().order_by('-scanned_at')  # or just '-id'
    return render(request, 'userProfile/manageBooks.html', {
        'books': books,
        'random_number': random.randint(0, 7)
    })

templates/userProfile/myBooks.html
{% include 'reusable/navbar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="{% static 'styleMybooks.css' %}">
  <meta charset="UTF-8">
  <title>My books</title>
</head>
<body>
  {% include 'reusable/styleCommon.html' with random_number=random_number %}
  <div class="backgroundPicture"></div>

  <h2 style="text-align:center;">Your books</h2>

  {% if books %}

    <form method="post" id="searchForm">
      {% csrf_token %}
      <input type="text" placeholder="Search..." name="search" id="searchInput">
    </form>

    {% for book in books %}
    <a href="/home/bookDetails/?isbn={{ book.isbn }}" class="book-card-link">
      <div class="book-card">
        <h4>{{ book.title }}</h4>
        <div class="date">Saved on {{ book.scanned_at|date:"M d, Y H:i" }}</div>
      </div>
    </a>
    {% endfor %}
  {% else %}
    <p style="text-align:center;">You haven't added any books yet.</p>
  {% endif %}
</body>
</html>

templates/userProfile/myRatings.html
{% include 'reusable/navbar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="{% static 'styleMyratings.css' %}">
  <meta charset="UTF-8">
  <title>My Ratings</title>
</head>
<body>
  {% include 'reusable/styleCommon.html' with random_number=random_number %}
  <div class="backgroundPicture"></div>
  <h2 style="text-align:center;">Your Ratings</h2>

  {% if ratings %}

  <form method="post" id="searchForm">
      {% csrf_token %}
      <input type="text" placeholder="Search..." name="search" id="searchInput">
    </form>

    {% for rating in ratings %}
    <a href="/home/bookDetails/?isbn={{ rating.isbn }}" class="rating-card-link">
      <div class="rating-card">
        <h4>{{ rating.title }}</h4>
        <div class="stars">
          {% for i in "12345" %}
            {% if i|add:"0" <= rating.rating %}
              ★
            {% else %}
              ☆
            {% endif %}
          {% endfor %}
        </div>
        <div class="date">Rated on {{ rating.rated_at|date:"M d, Y H:i" }}</div>
      </div>
    </a>
    {% endfor %}
  {% else %}
    <p style="text-align:center;">You haven't rated any books yet.</p>
  {% endif %}

</body>
</html>

templates/userProfile/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="{% static 'styleProfile.css' %}">
  <meta charset="UTF-8" />
  <title>My Profile</title>
</head>
<body>

  {% include 'reusable/navbar.html' %}
  {% include 'reusable/styleCommon.html' with random_number=random_number %}
  <div class="backgroundPicture"></div>

  <div class="container">
    <div class="profile-header">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_profile_picture">
          {% if user.userprofile.profile_picture %}
            {% if user.userprofile.display_mode == 'dark' %}
              <img src="{{ user.userprofile.profile_picture.url }}" alt="Profile Picture" style="filter: invert(1);">
            {% else %}
              <img src="{{ user.userprofile.profile_picture.url }}" alt="Profile Picture" style="filter: invert(0);">
            {% endif %}
          {% else %}
            <img src="{% static 'defaultpfp.jpg' %}" alt="Default Picture">
          {% endif %}
        </label>
        <input type="file" name="profile_picture" id="id_profile_picture" accept="image/*" style="display: none;" onchange="this.form.submit();">
      </form>

      <div class="username">{{ user.username }} - {{ user.userprofile.user_type }}</div>
    </div>

    <div class="sections">
      {% if user.userprofile.user_type == "User" %}
        <a href="{% url 'saved_books' %}" class="section-link">Saved Books</a>
        <a href="{% url 'my_ratings' %}" class="section-link">My Ratings</a>
      {% elif user.userprofile.user_type == "Librarie" %}
        <a href="{% url 'manage_books' %}" class="section-link">Manage Books</a>
      {% endif %}
    </div>

    <form method="post" action="{% url 'logout' %}" class="logout-form">
      {% csrf_token %}
      <button type="submit">Logout</button>
    </form>
  </div>

</body>
</html>